In [3]:
# Defining a numpy array
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
import numpy as np
arr = np.arange(10, 100, 5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [13]:
import numpy as np
x=np.empty([2,4],dtype=int)
print(x)

[[       44545824 140266969992416               0               0]
 [              0               0               0               0]]


In [14]:
import numpy as np
x = np.zeros([2,3])
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
import numpy as np
vector = np.linspace(0,20,5) # Returns numbers(float values) after every 5 numbers from 0 to 25
print(vector)

[ 0.  5. 10. 15. 20.]


In [21]:
import numpy as np
x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


In [24]:
import numpy as np
arr = np.zeros(8)
arr3d = arr.reshape((2,2,2))
print(arr3d)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [25]:
import numpy as np
arr = np.zeros(8)
arr3d = arr.reshape((2,2,2))
arr = arr3d.ravel()
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
import numpy as np
arr = np.arange(2, 20)
element = arr[6]
print(element)

8


In [33]:
import numpy as np
arr = np.arange(20)
arr_slice = slice(1, 10, 1)
print(arr[arr_slice])

[1 2 3 4 5 6 7 8 9]


In [34]:
import numpy as np
arr = np.arange(20)
print(arr[2:])

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [35]:
print(arr[:15])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [41]:
a = np.array([[1,2,3], [3,4,5], [4,5,6]])
print(a[0:2, 0:2])

[[1 2]
 [3 4]]


In [42]:
import pandas
listx = [10, 20, 30, 40]
table = pandas.DataFrame(listx)
print(table)

    0
0  10
1  20
2  30
3  40


In [43]:
import pandas
data = [{'a':1, 'b':2}, {'a':2,'b':4, 'c':8}]
table = pandas.DataFrame(data)
print(table)

   a  b    c
0  1  2  NaN
1  2  4  8.0


In [44]:
import pandas
data = [{'a': 1, 'b': 2}, {'a': 2, 'b': 4, 'c': 8}]
table = pandas.DataFrame(data, index=['first', 'second'])
print(table)

        a  b    c
first   1  2  NaN
second  2  4  8.0


In [46]:
import pandas
data = {'one': pandas.Series([1,2,3], index=['a','b','c']),
       'two': pandas.Series([1,2,3,4], index=['a','b','c','d'])}
table = pandas.DataFrame(data)
print(table)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


In [51]:
import pandas
data = {'one' : pandas.Series([1,2,3], index=['a','b','c']),
        'tow' : pandas.Series([1,2,3,4], index=['a','b','c','d'])
       }
table = pandas.DataFrame(data)
table['three'] = pandas.Series([10,20,30], index=['a','b','c'])
print(table)
print(table.loc['c'])
print(table.iloc[2])

   one  tow  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
one       3.0
tow       3.0
three    30.0
Name: c, dtype: float64
one       3.0
tow       3.0
three    30.0
Name: c, dtype: float64


In [56]:
import pandas
data = {'one': pandas.Series([1, 2, 3], index=['a', 'b', 'c']),
        'two': pandas.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
table = pandas.DataFrame(data)
table['three'] = pandas.Series([10, 20, 30], index=['a', 'b', 'c'])
print(table)
row  = pandas.DataFrame([[11, 13], [17, 19]], columns=['two', 'three'])
table = table.append(row) # Appends at the end of the table
print(table)

   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
0  NaN   11   13.0
1  NaN   17   19.0
