In [13]:
'''16. Write a python program to remove all entries with a
null value present.'''
import pandas as pd
df = pd.read_csv("lap_times.csv")
pd.isnull(df).any()
print(df.shape)
df = df.dropna(how='any',axis=0)
pd.isnull(df).any()
print(df.shape)
print(df)

(100, 5)
(97, 5)
    Position  Year         Make                           Model     Time
0          1  2009      Radical                          SR8 LM  06:48.0
1          2  2005      Radical                             SR8  06:56.1
2          3  2013      Porsche                      918 Spyder  06:57.0
3          4  2015  Lamborghini  Aventador LP 750-4 Superveloce  06:59.7
4          5  2015       Nissan                      GT-R Nismo  07:08.7
..       ...   ...          ...                             ...      ...
95        96  2003      Ferrari                          360 CS  07:56.0
96        97  2009      Ferrari                   California GT  07:56.0
97        98  2009      Porsche     Panamera Sport Chrono Turbo  07:56.0
98        99  2009      Porsche                  Panamera Turbo  07:56.0
99       100  2002    Chevrolet                    Corvette Z06  07:56.0

[97 rows x 5 columns]


In [21]:
'''17. Write a python program to replace all missing values in the dataset with a desired value accepted
from the user.'''
import pandas
import numpy as np
data = {'one': pandas.Series([1,2,5], index=['a','b','e']),
       'two': pandas.Series([1,2,3,4], index=['a','b','c','d'])
       }
table = pandas.DataFrame(data)
print("Before:\n",table)
print()
buff = 139
table['one'] = table['one'].replace(np.nan, buff)
table['two'].fillna(buff, inplace = True)
print("After:\n",table)

Before:
    one  two
a  1.0  1.0
b  2.0  2.0
c  NaN  3.0
d  NaN  4.0
e  5.0  NaN

After:
      one    two
a    1.0    1.0
b    2.0    2.0
c  139.0    3.0
d  139.0    4.0
e    5.0  139.0


In [29]:
'''18. Develop a Python code to impute a mean value to all
the null fields present in the data provided.'''
import pandas
import numpy as np
data = {'one':pandas.Series([1,2,5], index=['a','b','e']),
        'two':pandas.Series([1,2,3,4], index=['a','b','c','d'])
       }
table = pandas.DataFrame(data)
print("Before:\n",table)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(table)
imputed_data = imputer.transform(table.values)
print("\nAfter:\n", pandas.DataFrame(imputed_data, columns=['One','Two']))

Before:
    one  two
a  1.0  1.0
b  2.0  2.0
c  NaN  3.0
d  NaN  4.0
e  5.0  NaN

After:
         One  Two
0  1.000000  1.0
1  2.000000  2.0
2  2.666667  3.0
3  2.666667  4.0
4  5.000000  2.5


In [1]:
'''19. Write a pythonic method to convert categorical data
into numerical data.'''
import pandas as pd
data = {
    'Customer_id': pd.Series([1,2,3,4,5]),
    'Loan_type': pd.Series(['Home Loan','Personal Loan','Education Loan',
                           'Home Loan','Credit Loan']),
    'Income': pd.Series(['30K','25K','15K','40K','35K'])
}
loan_info = pd.DataFrame(data)
print(loan_info)
print()
loan_info = pd.get_dummies(loan_info, prefix_sep='_', drop_first=True)
print(loan_info)

   Customer_id       Loan_type Income
0            1       Home Loan    30K
1            2   Personal Loan    25K
2            3  Education Loan    15K
3            4       Home Loan    40K
4            5     Credit Loan    35K

   Customer_id  Loan_type_Education Loan  Loan_type_Home Loan  \
0            1                         0                    1   
1            2                         0                    0   
2            3                         1                    0   
3            4                         0                    1   
4            5                         0                    0   

   Loan_type_Personal Loan  Income_25K  Income_30K  Income_35K  Income_40K  
0                        0           0           1           0           0  
1                        1           1           0           0           0  
2                        0           0           0           0           0  
3                        0           0           0           0          

In [18]:
'''1. Write a Python program to fetch the title of the URL
specified.'''
from bs4 import BeautifulSoup
import requests
url = 'https://www.python.org/'
req = requests.session()
content = req.get(url)
soup = BeautifulSoup(content.text, 'html.parser')
#print(soup.prettify())
print(soup.title)

<title>Welcome to Python.org</title>


In [28]:
'''2. Write a Python program to print content of elements
that contain a specified string of a given web page.'''
import requests
import re
from bs4 import BeautifulSoup as bs
url = 'https://www.python.org/'
reqs = requests.get(url)
soup = bs(reqs.text, 'html.parser')
print("\n Content of elements that contain 'Python'string:")
str1 = soup.find_all(string=re.compile('Python'))
for txt in str1:
    print(" ".join(txt.split()))


 Content of elements that contain 'Python'string:
Welcome to Python.org
Python
The Python Network
Python Brochure
Python Books
Python Essays
Python Conferences
Python Logo
Python Wiki
Python News
Python Events
Python Events Archive
# Python 3: Fibonacci series up to n
The core of extensible programming is defining functions. Python allows mandatory and optional arguments, keyword arguments, and even arbitrary argument lists.
More about defining functions in Python 3
# Python 3: List comprehensions
Lists (known as arrays in other languages) are one of the compound data types that Python understands. Lists can be indexed, sliced and manipulated with other built-in functions.
More about lists in Python 3
# Python 3: Simple arithmetic
Calculations are simple with Python, and expression syntax is straightforward: the operators
More about simple math functions in Python 3
# Python 3: Simple output (with Unicode)
>>> print("Hello, I'm Python!")
Hello, I'm Python!
What is your name? Python Hi

In [32]:
'''3. Write a Python program to download an image from
the URL provided.'''
import requests
url = input('Enter URL of the image required:')
req = requests.get(url, stream=True)
req.raise_for_status()
with open('REQDownload.jpg', 'wb') as fd:
    for chunk in req.iter_content(chunk_size=50000):
        print('Received a chunk')
        fd.write(chunk)

Enter URL of the image required:https://docs.python.org/3/library/re.html
Received a chunk


In [34]:
'''4. Write a Python program to extract all URL's from the
specified link.'''
import requests
from bs4 import BeautifulSoup
url = input("Enter the URL to scrape:")
r = requests.get(url)
c = r.content
soup = BeautifulSoup(c,"html.parser")
for link in soup.find_all('a'):
    print(link.get('href'))

Enter the URL to scrape:https://docs.python.org/3/library/re.html
../genindex.html
../py-modindex.html
difflib.html
string.html
https://www.python.org/
../index.html
index.html
text.html
#module-re
#module-re
https://github.com/python/cpython/tree/3.8/Lib/re.py
stdtypes.html#str
stdtypes.html#bytes
exceptions.html#DeprecationWarning
exceptions.html#SyntaxError
#re-objects
https://pypi.org/project/regex/
#module-re
#regular-expression-syntax
#frie09
../howto/regex.html#regex-howto
#re.DOTALL
#re.MULTILINE
#re.MULTILINE
#re.MULTILINE
#re.ASCII
#re.LOCALE
https://unicode.org/reports/tr18/
exceptions.html#FutureWarning
exceptions.html#FutureWarning
#re.A
#re.I
#re.L
#re.M
#re.S
#re.X
#contents-of-module-re
#re.compile
#re.A
#re.I
#re.L
#re.M
#re.S
#re.X
#contents-of-module-re
#re.search
#re.match
#re.ASCII
#re.LOCALE
#re.ASCII
#re.LOCALE
#re.ASCII
#re.ASCII
#re.ASCII
#re.ASCII
#re.ASCII
#re.LOCALE
#re.ASCII
#re.LOCALE
#module-contents
enum.html#enum.IntFlag
#re.compile
#re-objects
#re.Patt

In [42]:
'''5. Write a Python program to test if a given page is
found or not on the server.'''
from urllib3.exceptions import HTTPError as BaseHTTPError
import requests

class RequestException(IOError):
    """This is the basis to raise errors"""
    
class HTTPError(RequestException):
    """An HTTP error occured."""
    
class URLError(RequestException):
    """An HTTP error occured."""
    
try:
    html = requests.get("http://www.example.com/")
except HTTPError as e:
    print("HTTP error")
except URLError as e:
    print("Server not found!")
else:
    print("HTML Details")
    print(html.content)

HTML Details
b'<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset="utf-8" />\n    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <style type="text/css">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 2em;\n        background-color: #fdfdff;\n        border-radius: 0.5em;\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        div {\n            margin: 0 auto;\n            width: auto;\n        }\n    }\n    </style>    \n</head>\n\n<body>

In [44]:
'''6. Write a python program to fetch data using a test API
and display it.'''
import requests
import json

print("-"*30)
print("This will show the most popular posts on social media")
print("-"*30)
data = requests.get("https://jsonplaceholder.typicode.com/posts").json()
for item in data[0]['title']:
    print('Post title:',(item))

------------------------------
This will show the most popular posts on social media
------------------------------
Post title: s
Post title: u
Post title: n
Post title: t
Post title:  
Post title: a
Post title: u
Post title: t
Post title:  
Post title: f
Post title: a
Post title: c
Post title: e
Post title: r
Post title: e
Post title:  
Post title: r
Post title: e
Post title: p
Post title: e
Post title: l
Post title: l
Post title: a
Post title: t
Post title:  
Post title: p
Post title: r
Post title: o
Post title: v
Post title: i
Post title: d
Post title: e
Post title: n
Post title: t
Post title:  
Post title: o
Post title: c
Post title: c
Post title: a
Post title: e
Post title: c
Post title: a
Post title: t
Post title: i
Post title:  
Post title: e
Post title: x
Post title: c
Post title: e
Post title: p
Post title: t
Post title: u
Post title: r
Post title: i
Post title:  
Post title: o
Post title: p
Post title: t
Post title: i
Post title: o
Post title:  
Post title: r
Post title: e
Po

In [46]:
'''7. Write a Python program to fetch visitor data on basis
of browser of the past 90 days on data.gov'''
import requests
r = requests.get("https://analytics.usa.gov/data/live/browsers.json")
print("90 days of visits broken down by browser for all sites:")
print(r.json()['totals']['browser'])

90 days of visits broken down by browser for all sites:
{'Chrome': 2533872868, 'Safari': 1842799197, 'Edge': 218081077, 'Internet Explorer': 191826159, 'Samsung Internet': 156852135, 'Firefox': 169453235, 'Safari (in-app)': 71782614, 'Android Webview': 59780833, 'Amazon Silk': 12201260, 'Opera': 13120471, 'Mercari_d': 5047347, 'UC Browser': 2649296, 'Opera Mini': 1955656, 'Mozilla Compatible Agent': 1434461, 'YaBrowser': 1180124, 'Coc Coc': 499802, 'Android Browser': 531686, 'ELB-HealthChecker': 563082, 'Amazon.com': 320767, 'Playstation 4': 203884, 'Puffin': 186634, 'Mozilla': 152901, 'BestBuy': 148978, 'SeaMonkey': 127671, 'ThousandEyes': 166448, 'UA-name:iOSDasherWebView; client-version: 2.54.2.1852.200411': 5905, 'BlackBerry': 83265, 'ulta-app-ios': 45834, 'Maxthon': 53798, 'Instagram 137.0.0.30.124': 5656, '(not set)': 22233, 'DoximityWebView': 90208, 'IRS - TRG19-01Loeim': 59617, 'United States Postal Service - TRG19-01Loeim': 59588, 'UA-name:iOSDasherWebView; client-version: 2.5

In [47]:
'''8. Write a Python program to verify SSL certificates for
HTTPS requests using requests module.'''
import requests
url=input("Enter a HTTPS URL: ")
print(requests.get(url))

Enter a HTTPS URL: https://www.crummy.com/software/BeautifulSoup/bs4/doc/#find-all
<Response [200]>


In [52]:
'''9. Write a Python program to get the number
earthquakes detected worldwide with magnitude
greater than 4.5 by the USGS.'''
import csv
import requests
csvurl = 'http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_month.csv'
sl = requests.get(csvurl).text.splitlines()
rows = list(csv.DictReader(sl))
print("The number of magnitude 4.5+ earthquakes detected worldwide by the USGS:", len(rows))

The number of magnitude 4.5+ earthquakes detected worldwide by the USGS: 455


In [55]:
'''10. Write a Python program to get movie name, year
and a brief summary of 10 random movies.'''
from bs4 import BeautifulSoup
import requests
import random
def get_imd_movies(url):
    page = requests.get(url)
    soup = BeautifulSoup(page.text, 'html.parser')
    movies = soup.find_all("td", class_="titleColumn")
    random.shuffle(movies)
    return movies
def get_imd_summary(url):
    movie_page = requests.get(url)
    soup = BeautifulSoup(movie_page.text, 'html.parser')
    return soup.find("div", class_="summary_text").contents[0].strip()
def get_imd_movie_info(movie):
    movie_title = movie.a.contents[0]
    movie_year = movie.span.contents[0]
    movie_url = 'http://www.imdb.com' + movie.a['href']
    return movie_title, movie_year, movie_url
def imd_movie_picker():
    ctr=0
    print("--------------------------------------------")
    for movie in get_imd_movies('http://www.imdb.com/chart/top'):
        movie_title, movie_year, movie_url = get_imd_movie_info(movie)
        movie_summary = get_imd_summary(movie_url)
        print(movie_title, movie_year)
        print(movie_summary)
        print("--------------------------------------------")
        ctr=ctr+1
        if (ctr==10):
            break;
if __name__ == '__main__':
    imd_movie_picker()

--------------------------------------------
The Prestige (2006)
After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.
--------------------------------------------
Toy Story (1995)
A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.
--------------------------------------------
12 Years a Slave (2013)
In the antebellum United States,
--------------------------------------------
Fanny och Alexander (1982)
Two young Swedish children experience the many comedies and tragedies of their family, the Ekdahls.
--------------------------------------------
L.A. Confidential (1997)
As corruption grows in 1950s Los Angeles, three policemen - one strait-laced, one brutal, and one sleazy - investigate a series of murders with their own brand of justice.
--------------------------------------------
Lawrence of Arabia (1962)
The story

In [59]:
'''11. Write a Python program to find the live weather
report (temperature, wind speed) of a given city.'''
import requests

def weather_data(query):
    res=requests.get('http://api.openweathermap.org/data/2.5/weather?'+query+'&APPID=b35975')
    return res.json();
def print_weather(result, city):
    print("{}'s temperature: {}°C ".format(city,result['main']['temp']))
    print("Wind speed: {} m/s".format(result['wind']['speed']))
    print("Description: {}".format(result['weather'][0]['description']))
    print("Weather: {}".format(result['weather'][0]['main']))
def main():
    city=input('Enter the city:')
    print()
    try:
        query='q='+city;
        w_data=weather_data(query);
        print_weather(w_data, city)
        print()
    except:
        print('City name not found...')
if __name__=='__main__':
    main()

Enter the city:Kathmandu

City name not found...


In [63]:
'''12. Write a Python program to list all language names
and number of related articles in the order they appear
in wikipedia.org.'''
import requests
from bs4 import BeautifulSoup
html = requests.get('https://www.wikipedia.org/')
bs = BeautifulSoup(html.text, "html.parser")
nameList = bs.findAll('a', {'class' : 'link-box'})
for name in nameList:
    print(name.get_text())


English
6 125 000+ articles


日本語
1 218 000+ 記事


Español
1 612 000+ artículos


Deutsch
2 458 000+ Artikel


Русский
1 644 000+ статей


Français
2 236 000+ articles


Italiano
1 623 000+ voci


中文
1 130 000+ 條目


Português
1 039 000+ artigos


Polski
1 420 000+ haseł



In [66]:
'''13. Write a Python program to count number of tweets
by a given Twitter account.'''
from bs4 import BeautifulSoup
import requests
handle = input('Input your account name on Twitter:')
temp = requests.get('https://twitter.com/'+handle)
bs = BeautifulSoup(temp.text,'lxml')

try:
    tweet_box = bs.find('li',{'class':'ProfileNav-item ProfileNav-item--tweets is-active'})
    tweets= tweet_box.find('a').find('span',{'class':'ProfileNav-value'})
    print("{} tweets {} number of tweets.".format(handle,tweets.get('data-count')))
except:
    print('Account name not found...')

Input your account name on Twitter:@dinesh99981


FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

In [69]:
'''14. Write a Python program to that retrieves an arbitrary
Wikipedia page of the users choice and creates a list of
links on that page.'''
import requests
from bs4 import BeautifulSoup
page=input("Enter Wikisearch Key: ")
html = requests.get("https://en.wikipedia.org/wiki/"+page)
bsObj = BeautifulSoup(html.text)
for link in bsObj.findAll("a"):
    if 'href' in link.attrs:
        print(link.attrs['href'])

Enter Wikisearch Key: dinesh
#mw-head
#searchInput
/wiki/Hindu_Mythology
/wiki/South_Asia
/wiki/Devanagari
/wiki/Hinduism
/wiki/Given_name
/wiki/Sanskrit
/wiki/Epithet
#cite_note-1
/wiki/Dinesh_(Kannada_actor)
/wiki/Dinesh_Baboo
/wiki/Dinesh_Chand
/wiki/Dinesh_Chandra_Sen
/wiki/Dinesh_D%27Souza
/wiki/Christian_apologist
/wiki/Dinesh_Gunawardena
/wiki/Dinesh_Gupta
/wiki/Dinesh_Karthik
/wiki/Dinesh_Kumar_(choreographer)
/wiki/Dinesh_Lamba
/wiki/Dinesh_Mongia
/wiki/Dinesh_Nandan_Sahay
/wiki/Dinesh_Nayak
/wiki/Dinesh_Patel
/wiki/Dinesh_Prasad_Singh
/wiki/Dinesh_Singh_(Uttar_Pradesh_politician)
/wiki/Dinesh_Singh_(Punjab_politician)
/w/index.php?title=Dinesh&action=edit&section=1
#cite_ref-1
/wiki/Monier_Monier-Williams
http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/2014/web/index.php
/wiki/Given_name
https://en.wikipedia.org/w/index.php?title=Special:WhatLinksHere/Dinesh&namespace=0
https://en.wikipedia.org/w/index.php?title=Dinesh&oldid=964155047
/wiki/Help:Category
/wiki/Category:

In [77]:
'''15. Write a Python program to get the number of
security alerts issued by US-CERT in the current
year.'''
import requests
from lxml import html
url = 'https://www.us-cert.gov/ncas/alerts'
doc = html.fromstring(requests.get(url).text)
print("The number of security alerts issued by US-CERT in the current year:")
print(len(doc.cssselect('.item-list li')))

The number of security alerts issued by US-CERT in the current year:
30


In [84]:
'''20. Write a pyhton program to convert all the
categorical data with ordinal values in the dataset into
numerical form.'''
import pandas as pd
from sklearn.preprocessing import LabelEncoder

data = {'Customer_id': pd.Series([1,2,3,4,5]),
'Loan_type': pd.Series(['Home Loan',
'Personal Loan',
'Education Loan',
'Home Loan',
'Credit Loan']),
'Income': pd.Series(['30K','25K','15','40K','35K'])}

loan_info = pd.DataFrame(data)
print(loan_info)
print()
labelencoder = LabelEncoder()
loan_info_upd = loan_info.apply(labelencoder.fit_transform)
print("Transformed Numerical value:")
print(loan_info_upd)

   Customer_id       Loan_type Income
0            1       Home Loan    30K
1            2   Personal Loan    25K
2            3  Education Loan     15
3            4       Home Loan    40K
4            5     Credit Loan    35K

Transformed Numerical value:
   Customer_id  Loan_type  Income
0            0          2       2
1            1          3       1
2            2          1       0
3            3          2       4
4            4          0       3


In [99]:
'''21. Implement OneHotEncoder from sklearn to convert
categorical data into numerically parsable data.'''
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = list(data)
print(values)
print()
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(data)
print("Integer Encoding:")
print(integer_encoded)
print()
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded),1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print("OneHotEncoding:")
print(onehot_encoded)
print()
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']

Integer Encoding:
[0 0 2 0 1 1 2 0 2 1]

OneHotEncoding:
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

['cold']
